version: "3.7"

services:
  runner:
    image: myoung34/github-runner:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      RUNNER_SCOPE:
      RUNNER_NAME_PREFIX: owtvn-local
      LABELS: owt-vn
      REPO_URL: https://github.com/nguyenhoanganhtuan1206/owt-backend-hands-on
      EPHEMERAL: 1
      ACCESS_TOKEN: $GITHUB_TOKEN
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
